### ISSUE TITLE
Allow defining constants from URL

### ISSUE THREAD

**Issue by simison** [Automattic/jurassic.ninja#125]
Would be neat to be able to define `JETPACK__API_BASE` when creating a site:

Something like:

```
https://jurassic.ninja/create/?JETPACK__API_BASE=https://my.example.com/jetpack.&jetpack-beta&branch=master&shortlived
```

Convo p1531237011000478-slack-jetpack-plugin

**Comment by oskosk** [comment]
Fixed by Automattic/companion#14  and  Automattic/companion#18
