### ISSUE TITLE
Problem when Cloning website from jurassic ninja

### ISSUE THREAD

**Issue by nunomiguelferreira** [Automattic/jurassic.ninja#195]
Hello,

I have used this service as provided in the website with great success, but when cloning via Duplicator to the final host I still get the notice the website will be destroyed in 7 days. I'd like to know if it is possible to remove it from the wp-admin page (and hopefully to have the confirmation that the website won't be destroyed in 7 days in the new host)

Thank you for the excellent prototyping tool by the way!

**Comment by oskosk** [comment]
The notice comes from an unlisted plugin called `companion`, You can uninstall it from the destination site.
