### ISSUE TITLE
Site creation fails when choosing WooCommerce Smooth Generator

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/jurassic.ninja#211]
When creating a new site with WooCommerce Smooth Generator selected, I get: `Oh No! There was a problem launching the new WP. (The API responded in a weird way).`

I've confirmed that this only happens when the `Include WooCommerce Smooth Generator` option is checked.

**Comment by jrick1229** [comment]
Per #221 - I also received this error without Smooth Generator checked, just FYI.

**Comment by oskosk** [comment]
Fixed by #229
