### ISSUE TITLE
Update dependencies to support PHP 8.0

### ISSUE THREAD

**Issue by ah-polash** [Automattic/jurassic.ninja#214]
I am trying Jurassic.ninja
I have piad server pilot 

when I trying to run command: composer install I am getting the following error.  (In server pilot i cannot select php version lower than 7.2 ) [Screenshot](https://prnt.sc/xgr68t)

bplugins@ubuntu-s-1vcpu-1gb-nyc3-01:~/apps/bplugins/public$ wp plugin install https://github.com/Automattic/jurassic.ninja/archive/master.zip
Downloading installation package from https://github.com/Automattic/jurassic.ninja/archive/master.zip...
Unpacking the package...
Installing the plugin...
Renamed Github-based project from 'jurassic.ninja-master' to 'jurassic.ninja'.
Plugin installed successfully.
Success: Installed 1 of 1 plugins.
bplugins@ubuntu-s-1vcpu-1gb-nyc3-01:~/apps/bplugins/public$ cd wp-content/plugins/jurassic.ninja
bplugins@ubuntu-s-1vcpu-1gb-nyc3-01:~/apps/bplugins/public/wp-content/plugins/jurassic.ninja$ composer install
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires nubs/random-name-generator 1.* -> satisfiable by nubs/random-name-generator[v1.0.0].
    - nubs/random-name-generator v1.0.0 requires php ~5.5 || ~7.0 -> your php version (8.0.1) does not satisfy that requirement.
  Problem 2
    - phpunit/phpunit[6.4.0, ..., 6.5.14] require php ^7.0 -> your php version (8.0.1) does not satisfy that requirement.
    - Root composer.json requires phpunit/phpunit ^6.4 -> satisfiable by phpunit/phpunit[6.4.0, ..., 6.5.14].

bplugins@ubuntu-s-1vcpu-1gb-nyc3-01:~/apps/bplugins/public/wp-content/plugins/jurassic.ninja$

How can i install ?

**Comment by kraftbj** [comment]
For problem 2, you can run `composer install --no-dev` since that requirement is not needed for running JN.

Problem 1, though, we depend on a third-party package that would need to be updated to work in PHP 8. I can check to see if they have an updated version, but at this time, I would suggest not using PHP 8 to run JN.

**Comment by kraftbj** [comment]
It looks like that dependency has a new version, so we'd need to update and test for it. No timeline for doing that though.
