### ISSUE TITLE
Can we use this without serverpilot ?

### ISSUE THREAD

**Issue by DianP** [Automattic/jurassic.ninja#220]
Hi There,
I just got some basic questions.

Can we use this script without a server pilot?
And if I use a server pilot, for each demo site instance, will it count as 1 app in the server pilot?

Thanks!

**Comment by kraftbj** [comment]
As it is, it expects ServerPilot. It would require work to redo the provision class if you want to use a different service or create your own.

Yes, each demo site counts as 1 app for ServerPilot. I realize their plans now charge per app, which is a bummer for this type of usage.
