### ISSUE TITLE
Cant create new site, asking to log in

### ISSUE THREAD

**Issue by akashxyz** [Automattic/jurassic.ninja#223]
When I click the **CREATE** button it asks me to log in via WordPress.com and after clicking **Log in with WordPress.com**.

It shows the below error even after I'm logged in to WordPress.com

![image](https://user-images.githubusercontent.com/61490132/110323213-50622580-803a-11eb-9711-4e70175de776.png)

**Comment by kraftbj** [comment]
That's intentional. The jurassic.ninja website was never meant to be a tool used by the general public. This plugin can be setup on your own server to provide a way for you to spin up development sites.
