### ISSUE TITLE
error message, "There has been an error cropping your image."

### ISSUE THREAD

**Issue by smiller7812** [Automattic/jurassic.ninja#224]
I am trying to upload a logo for a site.  I upload the logo image, then click select, then click Crop and I get this error:
"There has been an error cropping your image."

I've read that this could mean that the GD Library is not installed.
Is this installed for Jurassic.Ninja sites?

I also get this error when I press "Select and Crop" for the header image.

**Comment by kraftbj** [comment]
It depends on what your server has on it. On one of your sites, you can visit wp-admin/site-health.php?tab=debug and check under Media Handling.

`WP_Image_Editor_GD` is what is used on jurassic.ninja at this time.
