### ISSUE TITLE
Site creation fails for `woocommerce-beta-tester`

### ISSUE THREAD

**Issue by designsimply** [Automattic/jurassic.ninja#230]
Steps to reproduce:

1. Open `https://jurassic.ninja/create/?woocommerce-beta-tester&shortlived` in a browser.
1. Wait to see if a site is created successfully.

**Result:** if `woocommerce-beta-tester` is used, site creation fails with the following error in the browser console:

```
/wp-json/jurassic.ninja/create:1 Failed to load resource: the server responded with a status of 500 ()
```

![image](https://user-images.githubusercontent.com/1119271/117064847-f2715780-ace3-11eb-9075-fd435f517c41.png)

**Comment by oskosk** [comment]
This was fixed by #229
