### ISSUE TITLE
Migrating from Jurassic Ninja to new host

### ISSUE THREAD

**Issue by ajwinchell** [Automattic/jurassic.ninja#232]
I used jurassic.ninja to create a staging site. After I made some changes, I saved the site with the All-in-one WP Migration plugin, and imported that to a new, permanent installation. However, I am still getting the "Welcome to Jurassic Ninja! <URL> will be destroyed in 7 days." message.

How do I remove this / wipe the jurassic.ninja data from the site now that I'm no longer using it?

Thank you.

**Comment by ajwinchell** [comment]
It seems deleted the `companion` folder inside the plugins directory does the trick.

**Comment by oskosk** [comment]
> It seems deleting the companion folder inside the plugins directory does the trick.

👍

**Comment by bsolgr** [comment]
> 
> 
> It seems deleting the `companion` folder inside the plugins directory does the trick.

yes it does!
