### ISSUE TITLE
Server Config: Need to pass 500 error for php errors

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jurassic.ninja#233]
When a syntax error in PHP fatals, we should send an HTTP code of 500 back. I'm presuming something in the server config between nginx and PHP is not passing it correctly.

To reproduce:
* Fresh site with or without Jetpack.
* Activate Akismet
* Using SSH, modify akismet/akismet.php to produce a fatal error.

Expected: WordPress's fatal handling kick in and a HTTP 500 sent.

Actual: Error is direct printed to the browser and a HTTP 200 sent.

https://friendly-morpho.jurassic.ninja/ as an example site in that state.

cc: @oskosk do you think you can assist on this one? I haven't touched the actual guts of JN at this level before.

cc: @jessefriedman who discovered it.

**Comment by oskosk** [comment]
`WP_DEBUG` set to on swallows the standard behaviour bubbling up a 500 status.

**Comment by kraftbj** [comment]
Let me dig around. `WP_DEBUG` itself doesn't do that or at least with `WP_DEBUG` true and `WP_DEBUG_DISPLAY` false it still 500s as expected.

Even with `WP_DEBUG_DISPLAY` true, it should still pass the right error code. If that's a Core thing, then I'll look into that. Doesn't seem right.

**Comment by kraftbj** [comment]
It's a PHP bug https://bugs.php.net/bug.php?id=50921

If `display_errors` is set to 1/true, they intentionally don't send a 500 status code here https://github.com/php/php-src/blob/master/main/main.c#L1356

It sounds like it was an issue in Internet Explorer that if it was a 500 status and too short, it'd display their internal error page..

**Comment by kraftbj** [comment]
Closing this since it isn't a JN bug.
