### ISSUE TITLE
Sites are destroyed early without warning

### ISSUE THREAD

**Issue by mikejolley** [Automattic/jurassic.ninja#276]
Hello team!

Over a week ago I created 3 test sites on jurassic ninja, all identical:

pdFofs-JJ-p2#comment-866

I last logged into these sites March 30th:

pdFofs-JJ-p2#comment-902

It is now April 4th and 5 days have passed. Of the 3 sites, 2 have been deleted.

- https://vast-titi.jurassic.ninja
- https://minimum-tarsier.jurassic.ninja

https://hot-roborovski.jurassic.ninja survived and says 7 days on the dashboard but I cannot trust this estimate it seems.

Thanks

**Comment by oskosk** [comment]
Hi Mike. According to the db log:

* minimum-tarsier was created on 2023-03-23 14:39:16 (last logged in 2023-03-24)
* vast-titi.jurassic.ninja was created on 2023-03-23 14:29:13 (last logged in  2023-03-24 10:30:48)
* was created on 2023-03-23 15:12:53, but you did log in on 2023-03-29

**Note that for the site to remain alive, you need to actually log in, not just visit wp-admin (That's log out, then log in). Maybe that happened to be confusing?**

**Comment by mikejolley** [comment]
@oskosk That sounds like what happened. That does however mean that the "this site will be deleted in 7 days" notice was incorrect on the sites I only visited admin on.

**Comment by mikejolley** [comment]
@oskosk ah that explains it then :D Should I close this or repurpose it as a feature request to show the actual time remaining?

**Comment by oskosk** [comment]
Let's close it. There's already an issue (longstanding tho) https://github.com/Automattic/jurassic.ninja/issues/63
