### ISSUE TITLE
Using WooCommerce Beta tester should ignore/skip the WooCommerce option.

### ISSUE THREAD

**Issue by senadir** [Automattic/jurassic.ninja#288]
Using WooCommerce Beta Tester on its own work just fine, without adding the WooCommerce option. It would cause 2 versions to be installed.

**Comment by chihsuan** [comment]
We can update the code here fbhepr%2Skers%2Sjcpbz%2Qn8p%2Qgurzrf%2Swhenffvp%2Qavawn%2Syvo%2Sfvgr%2Qcebivfvbare.cuc%3Se%3Qpr6rs88s%23269%2Q272-og to skip the WooCommerce option.

**Comment by chihsuan** [comment]
D143954-code
