### ISSUE TITLE
Add option to install WooCommerce Trunk build

### ISSUE THREAD

**Issue by adrianduffell** [Automattic/jurassic.ninja#290]
Provide an option to install the WooCommerce using the trunk build. A zip can be obtained publicly from: https://betadownload.jetpack.me/data/woocommerce/trunk/woocommerce-dev.zip

It is possible to install WooCommerce trunk branch using WooCommerce Beta Tester live branch feature. However it has a limitation when testing WooCommerce install routines, because the live branch feature needs to perform an update over the latest version of WooCommerce. This means Jurassic Ninja runs the install routines from the latest version of WooCommerce, not trunk.

By installing the trunk build directly, we can test any changes to the install routines in trunk.

## Proposed UI

![Screen Shot 2024-03-29 at 10 02 02 pm](https://github.com/Automattic/jurassic.ninja/assets/9312929/37f0140e-8c36-4bb2-b603-f8b4021ecb5f)

**Comment by chihsuan** [comment]
> However it has a limitation when testing WooCommerce install routines, because the live branch feature needs to perform an update over the latest version of WooCommerce

I think this issue could possibly be fixed by https://github.com/Automattic/jurassic.ninja/issues/288.

**Comment by chihsuan** [comment]
D143954-code
