### ISSUE TITLE
Maintain a list of ready-to use sites

### ISSUE THREAD

**Issue by tyxla** [Automattic/jurassic.ninja#55]
With regards to e2e testing that use `jurassic.ninja` sites, it would be nice if we create and maintain a list of ready-to-use fresh `jurassic.ninja` sites (for example 20 of them). So every time a test needs a new Jetpack site, it pulls the oldest one from the list, removes it from the list, and initiates the creation of a new one.

See https://github.com/Automattic/wp-e2e-tests/issues/797

**Comment by simison** [comment]
I was just looking at the monster spin again and thought that this would be pretty neat! :-)
