### ISSUE TITLE
Update creation page message to reflect install will have Jetpack

### ISSUE THREAD

**Issue by tyxla** [Automattic/jurassic.ninja#64]
Currently, the `/create` page will always say `Launching a fresh WP with a Jetpack …`. I expected this to reflect whether the installation will have Jetpack or not, depending on the presence of a `nojetpack` parameter.

**Comment by kraftbj** [comment]
Edited the `/create` page to omit Jetpack. It's just a simple page that updates with a success or not message.

Going to close this since it is technically correct now, even if less specific. :)

A future iteration could output the various options for that generation.
